# Generated by Django 3.1.7 on 2021-03-20 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20210320_1142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='hits',
        ),
        migrations.DeleteModel(
            name='IPAddress',
        ),
    ]
